app.controller("CalendarCtrl", ["$scope", "$http", "$firebaseObject", "$location",
  function($scope, $http, $firebaseObject, $location) {

    var ref = new Firebase("https://8sfamily-calendar.firebaseio.com/");
    var authData = ref.getAuth();
    var uid;
    var selectedEventId;
    var draggedEventId;
    $scope.eventToEdit = '';
    $scope.draggedEvent = '';
      

    function checkAuthState(){
    // if already auth then load page
    if (authData) {
       getData(); 
    // if not auth, then show login modal
    } else {
      $('#loginModal').removeClass("hidden");
        }
    } 

    //when user submits login creds pass vals verify user info
    //and send message if incorrect or load page if correct
    $scope.logIn = function(email, password){
      ref.authWithPassword({
        "email": email,
        "password": password
      }, function(error, authData) {
        if (error) {
          alert('email or password was incorrect');
        } else {
          console.log("Authenticated successfully with payload:", authData);
          $("#loginModal").addClass("hidden");
          uid = ref.getAuth().uid;
          getData(); 
          }
        });
    }; // closes logIn function

    var getData = function(){
      $http.get('https://8sfamily-calendar.firebaseio.com/.json').success(function(data) {
        $scope.events = data;
        loadCalendar();
        populateCalendar(data);
      });
    };

    var loadCalendar = function(){
      $('#calendar').fullCalendar({

        schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives',

      // creates the buttons in the calendar header
        customButtons: {
          myCustomButton: {
            text: 'Log out!',
            click: function() {
               $location.path("/todo");
               $scope.$apply();

              //ref.unauth(); // this will log you off firebase authentication for now
            }
          }
        },
        header: {
          left: 'prev,next today myCustomButton addEvent  ',
          center: 'title',
          right: 'month,agendaWeek,basicDay,agendaDay' //placing a space between these will seperate buttons
        },
        stick: true,
        editable: true,
        displayEventEnd: true,
        dayClick: function(date, jsEvent, view) {
          d = date.format();
          $('#dater').text(d);
          $('#calendar').fullCalendar( 'gotoDate', d );
          // $('#calendar').fullCalendar('changeView', 'agendaDay');
          $('#addEventModal').removeClass("hidden");
          addEvent(d);
        },

        // allow event to be edited 
        eventClick: function(eventFromCalClick){ 
          $scope.eventToEdit =  $scope.events.events[eventFromCalClick.firebaseId]; 
          selectedEventId =  eventFromCalClick.firebaseId;      
          // console.log("event clicked: ", $scope.eventToEdit);
          $scope.$apply();
          $('#editEventModal').removeClass("hidden");
          editEvent();
          // console.log("event id ", eventFromCalClick.firebaseId);
          
        },
        eventRender: function(event, element) {
            $(element).tooltip({title: "Loc: " + event.where + "\n" + "Notes: " + event.comment});             
          },
        // drag an event to new day
        eventDrop: function(event, delta, revertFunc) {
          $scope.draggedEvent = $scope.events.events[event.firebaseId];          
          $scope.draggedEvent.date = event.start.format().substr(0, 10);
          draggedEventId = event.firebaseId;
          
          var draggedRef = new Firebase("https://8sfamily-calendar.firebaseio.com/events/" + draggedEventId);
            // update the firebase
            draggedRef.update($scope.draggedEvent);

    
          console.log("dragged: ",$scope.draggedEvent.date); 
          console.log("dragged Id: ",draggedEventId); 

         // alert(event.title + " was dropped on " + event.start.format());
          if (!confirm(event.title + " was dropped on " + event.start.format() + "\n\n" + "Are you sure about this change?")) {
            revertFunc();
          }
          location.reload();
        },
        // //with this you can handle the events that generated by droping any event to different position in the calendar
        // alertOnDrop: function(event, dayDelta, minuteDelta, allDay, revertFunc, jsEvent, ui, view){
        // $scope.$apply(function(){
        //   $scope.alertMessage = ('Event Droped to make dayDelta ' + dayDelta);
        //  });
        // }


      //       // put your options and callbacks here

        }); // closes .fullCalendar() / ends options area

    }; //closes loadCal

    // populates the calendar with fb event data
    var populateCalendar = function(fb){
      $scope.data = fb;
      var events = $scope.data.events;

      angular.forEach(events, function(event, key) {
        $('#calendar').fullCalendar('renderEvent', {
          title: event.title + '\n' + event.who.join(", "),
          start: new Date(event.date + ' ' + event.from),
          end: new Date(event.date + ' ' + event.to),
          who: event.who,
          where: event.where,
          comment: event.comment,
          firebaseId: key
        }, true);
      });
    };


    // get info from new event form and send it to firebase
    function addEvent(d) {

      // add clock for picking times
      $('.clockpicker').clockpicker({
        placement: 'top',
        align: 'left',
        autoclose: true,
        // donetext: 'Done'
      }); 

      $("#addEvent").click(function(e){
        e.preventDefault();
        // retrieve object from checkboxes
        var who = $scope.checkboxModel;
        // retrieve object values
        var whoItBe = [];

        angular.forEach(who, function(value, key) {
          if (who[key] !== false) {
            this.push(value);
          } 
        }, whoItBe); //console.log('whoItBe: ', whoItBe);
      
       
        var newEvent = {
          uid: uid, //FirebaseId,
          date: d,
          title: $("#eTitle").val(),
          where: $("#eLoc").val(),
          who: whoItBe,
          from: $("#eStart").val(),
          to: $("#eStop").val(),
          comment: $("#eComment").val()
        }; 

        // $('#calendar').fullCalendar( 'renderEvent', newEvent , 'stick' );
        // clear the form
        $('#addEventModal').find('input:text, input:password, select, textarea').val('');
        $('#addEventModal').find('input:radio, input:checkbox').prop('checked', false);
        // hide the modal
        $("#addEventModal").addClass("hidden");
     
        $.ajax({
          url: "https://8sfamily-calendar.firebaseio.com/events.json",
          method: "POST",
          data: JSON.stringify(newEvent)
        }).done(function(newData){

        }).fail(function(xhr, status, error){

        });  location.reload();
      }); //closes addEvent click function 
    } // closes addEvent()

    // edits an existing event and updates fb
    function editEvent() {

      // add clock for picking times
      $('.clockpicker').clockpicker({
        placement: 'top',
        align: 'left',
        autoclose: true,
        // donetext: 'Done'
      }); 

      $("#editEvent").click(function(e){
        e.preventDefault();
        // retrieve object from checkboxes
        var who = $scope.checkboxModel;
        // determine checkbox values
        var whoItBe = [];

        angular.forEach(who, function(value, key) {
        this.push(value);
        }, whoItBe);

        // assign the checkbox values to the edited event
        $scope.eventToEdit.who = whoItBe;

        //update this event in fb with edited info
        var editRef = new Firebase("https://8sfamily-calendar.firebaseio.com/events/" + selectedEventId);
        // update the firebase
        editRef.update($scope.eventToEdit);
          
        // hide modal and refresh page to calendar view with new data
        $("#editEventModal").addClass("hidden");
        location.reload();

      }); //closes editEvent click function 
    } // closes editEvent()

    // remove event from firebase
    $scope.removeEvent = function(key, event) {
      var removeRef = new Firebase("https://8sfamily-calendar.firebaseio.com/events/" + selectedEventId);
      removeRef.remove();
      location.reload();
    };


      // cancel addEvent action and exit form
    $scope.cancel =  function(){
      $('#addEventModal').find('input:text, input:password, select, textarea').val('');
      $('#addEventModal').find('input:radio, input:checkbox').prop('checked', false);
      $( 'editEventModal').find('input:text, input:password, select, textarea').val('');
      $( 'editEventModal', 'editEventModal').find('input:radio, input:checkbox').prop('checked', false);
      // hide the modal
      $("#addEventModal").addClass("hidden");
    };
    // cancel editEvent action and exit form
    $scope.cancelToo =  function(){
      $( 'editEventModal').find('input:text, input:password, select, textarea').val('');
      $( 'editEventModal', 'editEventModal').find('input:radio, input:checkbox').prop('checked', false);
      // hide the modal
      $("#editEventModal").addClass("hidden");
    };

 
    // enable selection of All or multiple individuals, but not both for an event
    $(".person").on('change', function(){ 
      $('#allIn').not(this).prop('checked', false);
    });
    $("#allIn").on('change', function(){ 
      $('.person').not(this).prop('checked', false);
    });


    // set value of All to false when individuals are checked
    $scope.updateToOne = function() {
      $scope.checkboxModel.all = false;
    }; //closes updateOne function

    // set the value of each individual to false if ALL is selected  
    $scope.updateToAll = function() {
      $scope.checkboxModel.rick = false;
      $scope.checkboxModel.susan = false;
      $scope.checkboxModel.neal = false;
      $scope.checkboxModel.sydney = false;
    }; //closes updateAll function
  







    checkAuthState();

}]); //closes lines 1-2



